version: "3"
services:
  cms:
    build:
      context: ./cms
      args:
        - NODE_ENV=development
    volumes:
      - ./cms/src:/app/src
  server:
    command: npm run start:dev
    build:
      context: ./server
      args:
        - NODE_ENV=development
    volumes:
      - ./server/src:/app/src
# TODO needs proper config for production/developement nodemon disable
